version: "3.8"
services:

  # Applications




  # Backing Services

  polar-postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

