services:

  # Applications

  warehouseservice:
    depends_on:
      - postgres
    image: "warehouseservice"
    container_name: "warehouseservice"
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/warehouse
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/warehouse


  # Backing Services

  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

